PXP-548: [CLI] Program does not exit on Ctrl-C key press
mindvalley/wukong-cli pull request #112
Opened 2023-06-12 09:01 UTC by jk-gan

## Summary

The root cause of this is because we have 2 `ctrl-c` handlers. And they are conflicted. I do a quick fix by removing the first `ctrl-c` handler (the one to show the cursor after `ctrl-c`) because I believe that unable to exit the cli with `ctrl-c` is much more annoying. 

Another solution I can think of is use other key to close the instances connection, so we won't have the conflict anymore. 

There are few ways to handle the signal too (https://tokio.rs/tokio/topics/shutdown), but this required to refactor some codes.

Ticket: [PXP-548](https://mindvalley.atlassian.net/browse/PXP-548)

## What's Changed

### Fixed
- [x] fix the `ctrl-c` signal don't exit the cli issue

2023-06-12 10:10 UTC, onimsha requested changes

2023-06-12 10:10 UTC, onimsha commented on src/main.rs
> +    // tokio::spawn(async move {
we should not leave commented code.

2023-06-12 10:10 UTC, onimsha commented on src/main.rs
> +    // tokio::spawn(async move {
If this is a WIP, or a TODO, better put a clear comment section about what we want to do in the future.

2023-06-13 02:16 UTC, onimsha approved these changes

2023-06-13 02:16 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/112#" title="Author self-approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/112#pullrequestreview-1476123385" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-06-13 02:16 UTC, merged