PXP-598: Add log tailing hotkey
mindvalley/wukong-cli pull request #148
Opened 2023-09-20 04:14 UTC by mfauzaan

## Summary

Introduce a new hot key, Ctrl+t (t stand for tailing), to allow pause / resume the logs tailing. 

When triggered, it will either pause the logs tailing operation, or resuming to tail the logs in the Logs panel.

Ticket: https://mindvalley.atlassian.net/browse/PXP-598

## What's Changed

- [ ] Add new hotkey `Ctrl+t`
- [ ] Code cleanup for logs UI to make it more readable

2023-09-20 04:14 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/148#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-09-21 04:52 UTC, sauron-droid commented
PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-09-25 01:38 UTC, onimsha submitted a review, later dismissed

2023-09-25 01:38 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/148#" title="Author self-approved">mfauzaan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/148#pullrequestreview-1641201924" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-09-25 05:09 UTC, jk-gan requested changes

2023-09-25 05:09 UTC, jk-gan commented on cli/src/commands/tui/app.rs
> +            None | Some(Action::ToggleLogsTailing) => match key {
```suggestion
            Some(Action::ToggleLogsTailing) => { ... }
            None => match key {
```
we can just match the `Action` instead

2023-09-25 05:39 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/148#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-09-25 05:39 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/148#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-09-25 05:40 UTC, mfauzaan commented on cli/src/commands/tui/app.rs
> +                    self.state.logs_severity = match self.state.logs_severity {
fix spelling errors from prev PR

2023-09-25 07:21 UTC, jk-gan approved these changes
LGTM

2023-09-25 07:21 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/148#pullrequestreview-1641485579" title="Approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/148#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-09-26 02:52 UTC, merged