PXP-671: [CLI] Implement the CloudSQL integration to the deployment status command
mindvalley/wukong-cli pull request #206
Opened 2024-03-12 04:28 UTC by jk-gan

## Summary

Ticket: [PXP-671](https://mindvalley.atlassian.net/browse/PXP-671)

## What's Changed

### Added
- [x] Display CloudSQL metrics in `wukong deployment status`

2024-03-12 04:28 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/206#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-03-13 09:04 UTC, Fadhil commented on cli/src/error.rs
> +                    format!("Check if your `config.toml` file is in valid TOML format.\nThis usually happen when the config file is accidentally modified or there is a breaking change to the cli conf
```suggestion
                    format!("Check if your `config.toml` file is in valid TOML format.\nThis usually happens when the config file has accidentally been modified or there is a breaking change to the cli config in the new version.\nYou may want to run {} to re-initialise configuration again.", "wukong init".yellow())
```

2024-03-13 09:05 UTC, Fadhil commented on cli/src/error.rs
> +                    format!("Check if the `.wukong.toml` file is in valid TOML format.\nThis usually happen when the config file is accidentally modified or there is a breaking change to the applicat
```suggestion
                    format!("Check if the `.wukong.toml` file is in valid TOML format.\nThis usually happens when the config file has accidentally been modified or there is a breaking change to the application config in the new version.\nYou may want to run {} to re-initialise configuration again.", "wukong application init".yellow())
```

2024-03-13 09:07 UTC, Fadhil commented on cli/src/commands/deployment/status.rs
>                      "* Appsignal status is not display because {}",
```suggestion
                    "* Appsignal status is not displayed because {}",
```

2024-03-13 09:07 UTC, Fadhil commented on cli/src/commands/deployment/status.rs
> +                colored_println!("* CloudSQL status is not display because {}", reason.bold());
```suggestion
                colored_println!("* CloudSQL status is not displayed because {}", reason.bold());
```

2024-03-13 09:09 UTC, Fadhil requested changes
Minor grammar changes

2024-03-13 09:13 UTC, Fadhil submitted a review, later dismissed

2024-03-13 09:13 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/206#pullrequestreview-1933530709" title="Approved">Fadhil</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/206#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-03-13 09:19 UTC, mfauzaan requested changes

2024-03-13 09:19 UTC, mfauzaan commented on cli/src/commands/application/init.rs
> +    eprintln!("Next is to configure the prod namespace for your application.");
why not use this way to reduce the number of lines

```suggestion
    eprintln!("\nNext is to configure the prod namespace for your application.\n");
```

2024-03-14 03:21 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/206#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-03-14 03:21 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/206#" title="Author self-approved">jk-gan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-03-14 03:22 UTC, onimsha commented on cli/src/commands/application/init.rs
> +    eprintln!();
```suggestion
```

2024-03-14 03:22 UTC, onimsha commented on cli/src/commands/application/init.rs
> +    eprintln!();
```suggestion
```

2024-03-14 03:23 UTC, mfauzaan approved these changes

2024-03-14 03:23 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/206#" title="Author self-approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/206#pullrequestreview-1935576239" title="Approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-03-14 03:46 UTC, merged