PXP-515: [CLI] Develop the config secrets diff command
mindvalley/wukong-cli pull request #86
Opened 2023-04-06 11:41 UTC by mfauzaan

## Summary
This command will pull the latest development secrets file from Bunker, compare it with the local version, and display the diff if there are any changes made.

<img width="727" alt="Screenshot 2023-04-06 at 7 35 38 PM" src="https://user-images.githubusercontent.com/25294487/230366346-f011f356-3498-4fb1-844b-cd43447be43f.png">

### Usage

To use the command, simply run: `wukong dev config diff`

Ticket: [PXP-515](https://mindvalley.atlassian.net/browse/PXP-515)

## What's Changed

- [ ]  Implement `wukong dev config diff` command.
- [ ] Add necessary utility functions to support the new command.
- [ ] Moved common functions from config push to utils file

2023-04-06 11:41 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-11 08:18 UTC, jk-gan requested changes

2023-04-11 08:31 UTC, jk-gan requested changes
Need integration testing too. Other than that, LGTM! Good job! The `dev config diff` looks beautiful!

2023-04-11 08:40 UTC, mfauzaan commented on src/commands/dev/config/utils.rs
> +                filtered_annotations.insert(file.to_string_lossy().to_string(), annotation);
oh hEyy, this one on bug PR: https://github.com/mindvalley/wukong-cli/pull/88

I'll send that one for review once this is merged. Didnt want to have so many context in one PR. Easier to review with smaller onces

2023-04-12 05:41 UTC, onimsha commented
> Need integration testing too. Other than that, LGTM! Good job! The `dev config diff` looks beautiful!

I'll also wait for the integration tests before review the PR again.

2023-04-13 05:07 UTC, onimsha approved these changes

2023-04-13 05:07 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/86#pullrequestreview-1382636709" title="Approved">onimsha</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-13 05:07 UTC, onimsha commented
LGTM 👍 .

@jk-gan please re-review this PR again.

2023-04-13 06:32 UTC, jk-gan requested changes

2023-04-13 06:32 UTC, jk-gan commented on Cargo.toml
> +serial_test = "2.0.0"
The `serial_test` is only for development environment, so this should be installed es `dev-dependencies`

2023-04-13 06:37 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-13 06:37 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-13 06:40 UTC, jk-gan approved these changes

2023-04-13 06:40 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#pullrequestreview-1382737614" title="Approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-13 06:53 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-13 06:53 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-13 07:04 UTC, jk-gan approved these changes
LGTM

2023-04-13 07:05 UTC, sauron-droid commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/wukong-cli/pull/86#pullrequestreview-1382769327" title="Approved">jk-gan</a>*, *<a href="https://github.com/mindvalley/wukong-cli/pull/86#" title="Author self-approved">mfauzaan</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fwukong-cli).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/wukong-cli/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-04-13 07:05 UTC, merged